### ISSUE TITLE
关于核显加速

### ISSUE THREAD

**Issue by jklTom** [Oosl/MSI-B460WIFI-10700F-RX550-4G#1]
我的CPU是i5 10600K，如果使用你的EFI能核显加速吗？显卡是R9 fury

**Comment by Oosl** [comment]
抱歉，不行的哦。我这个EFI没有做核显相关的补丁。建议参考我引用的[原仓库](https://github.com/QQ3233/Hackintosh-MSI-B460M-MORTAR-WIFI-i5-10500-iGPU-UHD630)
